### PR TITLE
Wrap delegate and undelegate

### PR DESCRIPTION
**Pull request by askmatey**
Check whether Backbone.utils.delegate or Backbone.utils.undelegate are functions

See paulmillr/exoskeleton#87

### CODE REVIEW

**Comment by askmatey** [comment]
Tested with: 

- chaplin `1.0.1`
- exoskeleton `0.7.0`
- Zepto `1.1.6`
- lodash `3.5.0`

See https://github.com/opendradio/app

**Comment by akre54** [comment]
Try `Backbone.utils?.delegate(this, eventName, ...)` or `Backbone.utils?.delegate?(this, eventName, ...)`

**Comment by askmatey** [comment]
@akre54 What do you mean exactly by that?

**Comment by akre54** [comment]
The coffeescript `?` "soak" operator does this without the need to wrap everything in a `_.isFunction` test. 

http://coffeescript.org/#try:Backbone.utils.delegate%3F(this%2C%20opts)

**Comment by akre54** [comment]
No need to close it. Just amend your pull request.

**Comment by askmatey** [comment]
I have accidentally removed my fork

**Pull request closed without merging**
