### PR TITLE
Reset byId properly. Closes GH-882

### PR DESCRIPTION
**Pull request by goshakkk**

### CODE REVIEW

**Comment by paulmillr** [comment]
Travis is broken.

**Comment by paulmillr** [comment]
Also let's freeze it.

**Comment by goshakkk** [comment]
Why freeze it? Exoskeleton in '_reset' just sets it to an empty object,
backbone is probably doing something similar.
On Fri, Mar 4, 2016 at 7:18 PM Paul Miller <notifications@github.com> wrote:

> Also let's freeze it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chaplinjs/chaplin/pull/890#issuecomment-192340845>.
>
-- 
Cheers,
Gosha

**Comment by paulmillr** [comment]
Let's use `{}` instead of `null` then.

**Comment by goshakkk** [comment]
Fixed

**Pull request merged**
